#!/usr/bin/env bash
# Auto-extracted from atone-consolidate.sh by the split refactor (2026-05-15).
# This file is intended to be sourced (not executed) by atone-consolidate.sh.
# Functions defined here rely on env vars + helpers from atone-common.sh
# and atone-consolidate/helpers.sh.

# ─── Curated compliments.md v2 (if affirm/ exists) ────────────────

build_curated_affirm() {
  if [ ! -f "$AFFIRM_EVENTS" ] || [ ! -s "$AFFIRM_EVENTS" ]; then
    _info "(no affirm/events.jsonl yet — skipping compliments.md regen)"
    return 0
  fi

  local out="$COMPLIMENTS"
  local rows
  rows=$(aggregate_slugs affirm "$AFFIRM_EVENTS")

  local scored
  scored=$(echo "$rows" | while IFS=$'\t' read -r src slug cnt sev_str ts cluster title latest_id; do
    [ -z "$slug" ] && continue
    local days score
    days=$(_days_since "${ts:0:10}")
    score=$(_score_for 1 "$days" "$cnt")
    printf '%s\t%s\t%s\t%s\t%s\n' "$score" "$slug" "$cnt" "$ts" "$title"
  done | sort -rn)

  {
    cat <<EOF
<!-- DERIVED FILE — regenerated by atone-consolidate.sh. Do not edit by hand. -->
<!-- Source: ~/.claude/affirm/events.jsonl · Last build: $NOW_UTC -->

# Affirmed Behaviors (curated)

Patterns the user explicitly approved — keep doing them. Ranked by recency × frequency.

## Top 10 most-affirmed

EOF
    local n=1
    echo "$scored" | head -10 | while IFS=$'\t' read -r score slug cnt ts title; do
      [ -z "$slug" ] && continue
      printf '%d. **%s** (%dx since %s) — %s\n' \
        "$n" "$slug" "$cnt" "${ts:0:10}" "$title"
      n=$((n+1))
    done
    echo
    echo "## Pointers"
    echo
    echo "- Full index: \`~/.claude/affirm/events.jsonl\`"
    echo "- Add: \`/affirm\` (or \`bash ~/.claude/scripts/affirm.sh add ...\`)"
  } > "$out.tmp" && mv "$out.tmp" "$out"
  _ok "wrote compliments.md v2"
}

