#!/usr/bin/env bash
# Auto-extracted from atone-consolidate.sh by the split refactor (2026-05-15).
# This file is intended to be sourced (not executed) by atone-consolidate.sh.
# Functions defined here rely on env vars + helpers from atone-common.sh
# and atone-consolidate/helpers.sh.

# ─── Index ────────────────────────────────────────────────────────

build_index() {
  local out="$DERIVED/index.md"
  {
    cat <<EOF
<!-- DERIVED FILE — regenerated by atone-consolidate.sh; do not edit. -->
<!-- Source: ~/.claude/atone/events.jsonl  Last build: $NOW_UTC -->

# atone — full event index

| date | id | sev | cl | slug | title |
|------|-----|----:|----|------|-------|
EOF
    if [ -f "${EVENTS_VIEW:-$EVENTS}" ] && [ -s "${EVENTS_VIEW:-$EVENTS}" ]; then
      jq -r '[.ts[:10], .id, .severity, (.cluster // "-"), .slug, (.title|tostring)[:80]] | @tsv' "${EVENTS_VIEW:-$EVENTS}" | \
        sort -r | awk -F'\t' '{ printf "| %s | %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5, $6 }'
    fi
  } > "$out.tmp" && mv "$out.tmp" "$out"
  _ok "wrote index.md ($(wc -l < "$out") lines)"
}

