#!/usr/bin/env bash
# Auto-extracted from atone-consolidate.sh by the split refactor (2026-05-15).
# This file is intended to be sourced (not executed) by atone-consolidate.sh.
# Functions defined here rely on env vars + helpers from atone-common.sh
# and atone-consolidate/helpers.sh.

build_clusters() {
  local cl name out base="${EVENTS_VIEW:-$EVENTS}" src
  src="$base"

  # Overlay the slug→cluster map onto events whose own .cluster is null, so the
  # append-only backlog buckets by family without rewriting history. This is the
  # same map /atone reads when assigning --cluster at write time. Operates on the
  # filtered view ($EVENTS_VIEW) so synthetic test slugs stay out of the counts.
  local map_file="$ATONE_DIR/cluster-map.tsv"
  if [ -f "$base" ] && [ -s "$base" ] && [ -f "$map_file" ]; then
    local map_json eff
    map_json=$(awk -F'\t' '$1 !~ /^#/ && NF>=2 {printf "%s\"%s\":\"%s\"", sep, $1, $2; sep=","}' "$map_file")
    eff="$DERIVED/.events-effective.jsonl"
    if jq -c --argjson map "{${map_json}}" '.cluster = (.cluster // ($map[.slug] // null))' "$base" > "$eff.tmp" 2>/dev/null; then
      mv "$eff.tmp" "$eff"; src="$eff"
    fi
  fi

  for cl in A B C D E; do
    name=$(cluster_name "$cl")
    out="$DERIVED/clusters/$cl-$(cluster_slug "$cl").md"
    {
      cat <<EOF
<!-- DERIVED — regenerated by atone-consolidate.sh -->

# Cluster $cl — $name

EOF
      if [ -f "$src" ] && [ -s "$src" ]; then
        local slug_count
        slug_count=$(jq -r --arg cl "$cl" 'select(.cluster == $cl) | .slug' "$src" | sort -u | wc -l | tr -d ' ')
        local event_count
        event_count=$(jq -r --arg cl "$cl" 'select(.cluster == $cl) | .id' "$src" | wc -l | tr -d ' ')
        printf '%d distinct slugs, %d total events.\n\n' "$slug_count" "$event_count"
        echo "## Member slugs"
        echo
        jq -r --arg cl "$cl" 'select(.cluster == $cl) | .slug' "$src" | sort | uniq -c | sort -rn | \
          awk '{ printf "- %dx `%s`\n", $1, $2 }'
        echo
        echo "## Recent occurrences (last 10)"
        echo
        echo "| date | id | slug | title |"
        echo "|------|-----|------|-------|"
        jq -r --arg cl "$cl" 'select(.cluster == $cl) | [.ts[:10], .id, .slug, (.title|tostring)[:60]] | @tsv' "$src" | \
          sort -r | head -10 | awk -F'\t' '{ printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4 }'
      fi
    } > "$out.tmp" && mv "$out.tmp" "$out"
  done
  _ok "wrote 5 cluster files"
}

