#!/usr/bin/env bash
# Auto-extracted from atone-consolidate.sh by the split refactor (2026-05-15).
# This file is intended to be sourced (not executed) by atone-consolidate.sh.
# Functions defined here rely on env vars + helpers from atone-common.sh
# and atone-consolidate/helpers.sh.

# ─── Curated mistake-patterns.md v2 ───────────────────────────────

build_curated_atone() {
  local out="$CURATED"
  local rows
  rows=$(aggregate_slugs atone "${EVENTS_VIEW:-$EVENTS}")

  # Score and rank
  local scored
  scored=$(echo "$rows" | while IFS=$'\t' read -r src slug cnt sev_str ts cluster title latest_id; do
    [ -z "$slug" ] && continue
    local sev_int days score
    sev_int=$(_sev_max_to_int "$sev_str")
    days=$(_days_since "${ts:0:10}")
    score=$(_score_for "$sev_int" "$days" "$cnt")
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$score" "$slug" "$sev_str" "$cnt" "$cluster" "$ts" "$title"
  done | sort -rn)

  local top5 top20 archive
  top5=$(echo "$scored" | head -5)
  top20=$(echo "$scored" | head -20)
  archive=$(echo "$scored" | sed -n '21,500p')

  {
    cat <<EOF
<!-- DERIVED FILE — regenerated by atone-consolidate.sh. Do not edit by hand. -->
<!-- Source: ~/.claude/atone/events.jsonl · Last build: $NOW_UTC -->
<!-- Full index: ~/.claude/atone/derived/index.md · Archive: derived/archive.md -->
<!-- Add an event: bash ~/.claude/scripts/atone.sh add ... (or invoke /atone) -->

# Mistake Patterns (curated)

**Read at session start when working on:** sub-agent dispatch, git/staging,
CSS/UI, error handling, frontend deploys, file refactors, comment hygiene.
Hot 5 first; top 20 below; archive (rank 21+) for the rest.

## The honest floor (what these patterns can and cannot fix)

Roughly 60-65% of recent recurrence is a cognitive-model ceiling, not a gap a
gate can close. The two biggest recurrers, structural-claim-without-reading-code
and speculative-abstractions, are assertions made in natural-language reasoning
with no greppable tool-call surface, so no PreToolUse hook can catch them at the
moment they happen. The other ~35-40% is mechanically gateable (the rg -r
footgun, comment noise, no-persistence sub-agent dispatches) and those gates
exist and bind.

So the honest target is: gateable classes driven to near zero, cognitive classes
down 20-35%, not to zero. Adding more rules or reminders aimed at the cognitive
classes scores near zero on behaviour change, because awareness is already
saturated; the lever there is the same-session circuit breaker (a hard stop at
the proven repeat point), not another reminder. The measured truth per slug,
recurrence before vs after each intervention shipped, lives in
\`atone/derived/intervention-efficacy.json\`. Read that, not the raw recurrence
count, before concluding any fix worked.

(Floor figure from the 2026-06-25 atone-recurrence audit + MAGI deliberation.)

## TL;DR — top 5 (severity × recency × frequency)

EOF
    local n=1
    echo "$top5" | while IFS=$'\t' read -r score slug sev cnt cluster ts title; do
      [ -z "$slug" ] && continue
      printf '%d. **%s** (%s, %dx since %s) — %s\n' \
        "$n" "$slug" "$sev" "$cnt" "${ts:0:10}" "$title"
      n=$((n+1))
    done

    cat <<EOF

## Top 20 patterns (ranked)

EOF
    local n=1
    echo "$top20" | while IFS=$'\t' read -r score slug sev cnt cluster ts title; do
      [ -z "$slug" ] && continue
      cluster_str="${cluster:--}"
      printf '### %d. %s — \`cluster:%s\` \`sev:%s\` \`count:%d\`\n' \
        "$n" "$slug" "$cluster_str" "$sev" "$cnt"
      printf '%s\n\n' "$title"
      printf 'Latest: %s · Index: [%s](atone/derived/index.md)\n\n' "${ts:0:10}" "$slug"
      n=$((n+1))
    done

    cat <<'EOF'
## Clusters

- **A — Ungrounded assertion**: claim before checking. → [clusters/A](atone/derived/clusters/)
- **B — Claim-ready-before-runtime**: shipped without executing. → [clusters/B](atone/derived/clusters/)
- **C — Literal-list-as-action**: user list executed literally. → [clusters/C](atone/derived/clusters/)
- **D — Output-shape laziness**: didn't render/inspect before judging. → [clusters/D](atone/derived/clusters/)
- **E — Convention-blind code**: ignored project rules. → [clusters/E](atone/derived/clusters/)

## Pointers

- Full index (every event): `~/.claude/atone/derived/index.md`
- Archive (rank 21+): `~/.claude/atone/derived/archive.md`
- RCAs (S3 post-mortems): `~/.claude/atone/rca/`
- Add new event: `/atone` (or `bash ~/.claude/scripts/atone.sh add ...`)
EOF
  } > "$out.tmp" && mv "$out.tmp" "$out"
  _ok "wrote mistake-patterns.md v2 (top 5 + top 20)"

  # Archive overflow
  {
    cat <<EOF
<!-- DERIVED FILE — regenerated by atone-consolidate.sh -->
# atone archive — patterns ranked 21+

EOF
    local n=21
    echo "$archive" | while IFS=$'\t' read -r score slug sev cnt cluster ts title; do
      [ -z "$slug" ] && continue
      printf '%d. **%s** (%s, %dx, c:%s) — %s\n' \
        "$n" "$slug" "$sev" "$cnt" "${cluster:--}" "$title"
      n=$((n+1))
    done
  } > "$DERIVED/archive.md.tmp" && mv "$DERIVED/archive.md.tmp" "$DERIVED/archive.md"
  _ok "wrote archive.md"
}

