#!/usr/bin/env bash
# zreclaim — recon and safe cleanup of reproducible cache/build data.
#
# Finds accumulated disposable data (node/python/rust build dirs, tool caches),
# ranks it biggest-first, and lets you delete a pareto selection. Also reports
# large files checked into git so you can decide per file. Everything it will
# delete is reproducible; git-tracked dirs are excluded, so it never removes
# something you committed on purpose.
#
# Written for macOS system bash 3.2 (no associative arrays). Sources the
# std::claude::tui library for the interactive picker and confirm.
set -uo pipefail

VERSION="1.1.0"
SELF="zreclaim"

# ── std::claude::tui ─────────────────────────────────────────────────────────
_tuidir="$HOME/.claude/scripts/tui"
# shellcheck disable=SC1090
{ . "$_tuidir/colors.sh"; . "$_tuidir/require.sh"; . "$_tuidir/tty.sh"; . "$_tuidir/pick.sh"; } 2>/dev/null || true
command -v tui_colors_init >/dev/null 2>&1 && tui_colors_init || { B=''; Y=''; C=''; D=''; R=''; G=''; RED=''; MAG=''; BLU=''; }

# ── small helpers ────────────────────────────────────────────────────────────
die()  { printf '%s%s: %s%s\n' "${RED}" "$SELF" "$*" "${R}" >&2; exit 1; }
warn() { printf '%s%s%s\n' "${Y}" "$*" "${R}" >&2; }

human_kb() {  # KB → human size
  local kb=${1:-0}
  case "$kb" in ''|*[!0-9]*) kb=0 ;; esac
  if   [ "$kb" -ge 1048576 ]; then awk "BEGIN{printf \"%.1fG\", $kb/1048576}"
  elif [ "$kb" -ge 1024 ];    then awk "BEGIN{printf \"%.1fM\", $kb/1024}"
  else printf '%dK' "$kb"; fi
}

# regenerate hint by category basename (shown in reports, never acted on)
regen_hint() {
  case "$1" in
    node_modules) echo "npm/pnpm/yarn install" ;;
    .next|dist|build|.turbo|.svelte-kit|.nuxt|.output|.astro|.vite|.parcel-cache) echo "rebuild" ;;
    .venv|venv) echo "uv sync / pip install" ;;
    __pycache__|.pytest_cache|.mypy_cache|.ruff_cache|.tox) echo "regenerated on next run" ;;
    target) echo "cargo build" ;;
    .gradle) echo "gradle build" ;;
    .playwright-mcp|playwright-report|test-results) echo "regenerated by next test run" ;;
    .cache|coverage|.nyc_output|DerivedData|.sass-cache|.webpack|.angular|.dart_tool) echo "regenerated on next run" ;;
    *) echo "reproducible" ;;
  esac
}

# ── root resolution + protected-root refusal ─────────────────────────────────
resolve_root() {
  local r=$1 abs
  abs=$(cd "$r" 2>/dev/null && pwd -P) || die "not a directory: $r"
  case "$abs" in
    / | "$HOME" | /Users | /System | /Library | /usr | /usr/* | /etc | /bin | /sbin | /var | /opt | /private | /Applications)
      die "refusing to operate on protected root: $abs (point it at a project dir)" ;;
  esac
  printf '%s\n' "$abs"
}

# ── candidate discovery ──────────────────────────────────────────────────────
# raw_candidates ROOT — matched cache/build dirs, pruned (no descent), .git skipped.
raw_candidates() {
  local root=$1
  find "$root" \
    -type d -name .git -prune -o \
    -type d \( \
      -name node_modules -o -name .next -o -name dist -o -name build -o \
      -name .turbo -o -name .parcel-cache -o -name .svelte-kit -o -name .nuxt -o \
      -name .output -o -name .astro -o -name .vite -o \
      -name .venv -o -name venv -o -name __pycache__ -o -name .pytest_cache -o \
      -name .mypy_cache -o -name .ruff_cache -o -name .tox -o \
      -name .gradle -o -name .cache -o -name coverage -o -name .nyc_output -o \
      -name DerivedData -o -name target -o \
      -name .playwright-mcp -o -name playwright-report -o -name test-results -o \
      -name .sass-cache -o -name .webpack -o -name .angular -o -name .dart_tool \
    \) -prune -print 2>/dev/null
}

# is_candidate_name BASE PARENT — the closed allowlist gate (defense in depth for delete).
is_candidate_name() {
  local base=$1 parent=$2
  case "$base" in
    node_modules|.next|dist|build|.turbo|.parcel-cache|.svelte-kit|.nuxt|.output|.astro|.vite) return 0 ;;
    .venv|venv|__pycache__|.pytest_cache|.mypy_cache|.ruff_cache|.tox) return 0 ;;
    .gradle|.cache|coverage|.nyc_output|DerivedData) return 0 ;;
    .playwright-mcp|playwright-report|test-results|.sass-cache|.webpack|.angular|.dart_tool) return 0 ;;
    target) [ -f "$parent/Cargo.toml" ] && return 0 || return 1 ;;
    *) return 1 ;;
  esac
}

# is_tracked PATH — 0 if git tracks it (→ excluded from deletion), 1 otherwise.
is_tracked() {
  local p=$1 repo rel
  repo=$(git -C "${p%/*}" rev-parse --show-toplevel 2>/dev/null) || return 1
  rel=${p#"$repo"/}
  [ "$rel" = "$p" ] && rel=${p##*/}
  [ -n "$(git -C "$repo" ls-files -- "$rel" 2>/dev/null | head -1)" ]
}

# collect OUT_DEL OUT_TRK ROOTS... — classify every candidate into deletable vs
# excluded-because-tracked. Lines: size_kb<TAB>category<TAB>abspath.
collect() {
  local out_del=$1 out_trk=$2; shift 2
  : > "$out_del"; : > "$out_trk"
  local root p base parent kb
  for root in "$@"; do
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      base=${p##*/}; parent=${p%/*}
      is_candidate_name "$base" "$parent" || continue
      kb=$(du -sk "$p" 2>/dev/null | awk '{print $1}')
      case "$kb" in ''|*[!0-9]*) kb=0 ;; esac
      if is_tracked "$p"; then
        printf '%s\t%s\t%s\n' "$kb" "$base" "$p" >> "$out_trk"
      else
        printf '%s\t%s\t%s\n' "$kb" "$base" "$p" >> "$out_del"
      fi
    done <<EOF
$(raw_candidates "$root")
EOF
  done
}

# ── pareto selection ─────────────────────────────────────────────────────────
# pareto SORTED_DESC_FILE PCT — echo the fewest top lines whose cumulative size
# reaches PCT% of the total. size_kb is field 1.
pareto() {
  local file=$1 pct=$2 total=0 acc=0 target
  total=$(awk -F'\t' '{s+=$1} END{print s+0}' "$file")
  [ "$total" -gt 0 ] || { cat "$file"; return; }
  target=$(awk "BEGIN{printf \"%d\", $total*$pct/100}")
  awk -F'\t' -v t="$target" 'BEGIN{a=0} {a+=$1; print} a>=t{exit}' "$file"
}

# ── deletion (rm by default, --trash opt-in) ─────────────────────────────────
DELETE_MODE="rm"   # or "trash"
do_delete() {  # revalidates each path before removing (defense in depth)
  local p=$1 base parent
  base=${p##*/}; parent=${p%/*}
  [ -d "$p" ] || { warn "skip (not a dir): $p"; return 1; }
  if ! is_candidate_name "$base" "$parent"; then
    warn "REFUSED (not an allowlisted cache/build dir): $p"; return 1
  fi
  if is_tracked "$p"; then
    warn "REFUSED (tracked in git): $p"; return 1
  fi
  if [ "$DELETE_MODE" = trash ]; then
    trash "$p" 2>/dev/null || { warn "trash failed: $p"; return 1; }
  else
    rm -rf "$p" || { warn "rm failed: $p"; return 1; }
  fi
  return 0
}

# ── git helpers for reporting ────────────────────────────────────────────────
find_repos() {  # abspaths of git repo roots under a root (main repos; .git dir)
  local root=$1
  find "$root" -type d -name .git -prune -print 2>/dev/null | while IFS= read -r g; do
    printf '%s\n' "${g%/.git}"
  done
}

# large_loose_files ROOT MIN_MB — files >= MIN_MB that are NOT inside a deletable
# cache dir and NOT under .git. These are flagged, never deleted (a stray video,
# dataset, dump, log, etc. the user should decide about). Emits: bytes<TAB>path.
large_loose_files() {
  local root=$1 mb=$2
  find "$root" \
    -type d -name .git -prune -o \
    -type d \( \
      -name node_modules -o -name .next -o -name dist -o -name build -o \
      -name .turbo -o -name .parcel-cache -o -name .svelte-kit -o -name .nuxt -o \
      -name .output -o -name .astro -o -name .vite -o \
      -name .venv -o -name venv -o -name __pycache__ -o -name .pytest_cache -o \
      -name .mypy_cache -o -name .ruff_cache -o -name .tox -o \
      -name .gradle -o -name .cache -o -name coverage -o -name .nyc_output -o \
      -name DerivedData -o -name target -o \
      -name .playwright-mcp -o -name playwright-report -o -name test-results -o \
      -name .sass-cache -o -name .webpack -o -name .angular -o -name .dart_tool \
    \) -prune -o \
    -type f -size +"${mb}"M -print 2>/dev/null | while IFS= read -r f; do
      local sz; sz=$(stat -f%z "$f" 2>/dev/null || stat -c%s "$f" 2>/dev/null)
      case "$sz" in ''|*[!0-9]*) continue ;; esac
      printf '%s\t%s\n' "$sz" "$f"
    done
}

# ── commands ─────────────────────────────────────────────────────────────────
cmd_scan() {
  local json=0 min=1 big=50; local roots=()
  while [ $# -gt 0 ]; do case "$1" in
    --json) json=1; shift ;;
    --plain) shift ;;                 # colors already gated by TTY
    --min) min=$2; shift 2 ;;         # itemize floor (MB); smaller dirs summarized
    --big) big=$2; shift 2 ;;         # large-loose-file threshold (MB)
    -*) die "scan: unknown option $1" ;;
    *) roots+=("$1"); shift ;;
  esac; done
  [ ${#roots[@]} -gt 0 ] || roots=(".")
  local rr=(); local r a; for r in "${roots[@]}"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done

  local del trk; del=$(mktemp); trk=$(mktemp)
  collect "$del" "$trk" "${rr[@]}"
  local delsorted; delsorted=$(mktemp); sort -t$'\t' -k1,1 -rn "$del" > "$delsorted"

  if [ "$json" = 1 ]; then
    scan_json "$delsorted" "$trk" "${rr[@]}"
    rm -f "$del" "$trk" "$delsorted"; return 0
  fi

  local total; total=$(awk -F'\t' '{s+=$1} END{print s+0}' "$delsorted")
  printf '%s%s%s  %sreclaimable: %s%s\n' "$B" "zreclaim scan" "$R" "$G" "$(human_kb "$total")" "$R"
  printf '%sroots:%s %s\n\n' "$D" "$R" "${rr[*]}"

  local min_kb=$((min*1024))
  if [ -s "$delsorted" ]; then
    printf '%s%-9s  %-16s %s (>= %sMB)%s\n' "$B" "SIZE" "CATEGORY" "PATH" "$min" "$R"
    awk -F'\t' -v f="$min_kb" '$1>=f {print $1"\t"$2"\t"$3}' "$delsorted" | while IFS=$'\t' read -r kb cat p; do
      printf '%s%-9s%s  %s%-16s%s %s\n' "$G" "$(human_kb "$kb")" "$R" "$C" "$cat" "$R" "$p"
    done
    local sn stot
    sn=$(awk -F'\t' -v f="$min_kb" '$1<f {n++} END{print n+0}' "$delsorted")
    stot=$(awk -F'\t' -v f="$min_kb" '$1<f {s+=$1} END{print s+0}' "$delsorted")
    [ "$sn" -gt 0 ] && printf '%s  + %d smaller dir(s) < %sMB, totaling %s (raise/lower with --min)%s\n' "$D" "$sn" "$min" "$(human_kb "$stot")" "$R"
    printf '\n%sby category:%s\n' "$B" "$R"
    awk -F'\t' '{a[$2]+=$1; n[$2]++} END{for(k in a) print a[k]"\t"k"\t"n[k]}' "$delsorted" \
      | sort -t$'\t' -k1,1 -rn | while IFS=$'\t' read -r kb cat n; do
        printf '  %s%-9s%s %-16s %s%d dirs%s  (%s%s%s)\n' "$G" "$(human_kb "$kb")" "$R" "$cat" "$D" "$n" "$R" "$D" "$(regen_hint "$cat")" "$R"
      done
    printf '\n  %stotal reclaimable: %s%s%s\n' "$B" "$G" "$(human_kb "$total")" "$R"
  else
    printf '%sNo reclaimable cache/build data found.%s\n' "$D" "$R"
  fi

  if [ -s "$trk" ]; then
    printf '\n%s⚠ tracked in git (EXCLUDED — you committed these; delete manually if intended):%s\n' "$Y" "$R"
    sort -t$'\t' -k1,1 -rn "$trk" | while IFS=$'\t' read -r kb cat p; do
      printf '  %s%-9s%s %-16s %s\n' "$Y" "$(human_kb "$kb")" "$R" "$cat" "$p"
    done
  fi

  # .git sizes (gc-able via `zreclaim gc`)
  local repos; repos=$(mktemp); for r in "${rr[@]}"; do find_repos "$r"; done > "$repos"
  if [ -s "$repos" ]; then
    printf '\n%sgit repos (.git size — reclaim with `%s gc`):%s\n' "$B" "$SELF" "$R"
    while IFS= read -r repo; do
      [ -n "$repo" ] || continue
      local gk; gk=$(du -sk "$repo/.git" 2>/dev/null | awk '{print $1}')
      printf '  %s%-9s%s %s\n' "$MAG" "$(human_kb "${gk:-0}")" "$R" "$repo"
    done < "$repos"
  fi

  # large tracked files (report only)
  printf '\n%slarge files tracked in git (report only — decide per file):%s\n' "$B" "$R"
  local bigf; bigf=$(mktemp)
  while IFS= read -r repo; do
    [ -n "$repo" ] || continue
    git -C "$repo" ls-tree -r -l HEAD 2>/dev/null | while IFS= read -r line; do
      local pre path sz
      pre=${line%%$'\t'*}; path=${line#*$'\t'}
      sz=$(printf '%s\n' "$pre" | awk '{print $4}')
      case "$sz" in ''|*[!0-9]*) continue ;; esac
      [ "$sz" -ge 5242880 ] && printf '%s\t%s/%s\n' "$sz" "$repo" "$path"
    done
  done < "$repos" > "$bigf"
  if [ -s "$bigf" ]; then
    sort -t$'\t' -k1,1 -rn "$bigf" | head -20 | while IFS=$'\t' read -r sz p; do
      local kb=$((sz/1024))
      printf '  %s%-9s%s %s\n' "$RED" "$(human_kb "$kb")" "$R" "$p"
    done
    printf '  %sto untrack: git rm --cached <f> + add to .gitignore; to purge history: git filter-repo%s\n' "$D" "$R"
  else
    printf '  %snone over 5M.%s\n' "$D" "$R"
  fi

  # large loose files OUTSIDE deletion scope (report only — you decide)
  printf '\n%slarge files not auto-deletable (>= %sMB, report only — you decide):%s\n' "$B" "$big" "$R"
  local loose; loose=$(mktemp)
  for r in "${rr[@]}"; do large_loose_files "$r" "$big"; done > "$loose"
  if [ -s "$loose" ]; then
    sort -t$'\t' -k1,1 -rn "$loose" | head -25 | while IFS=$'\t' read -r sz p; do
      printf '  %s%-9s%s %s\n' "$RED" "$(human_kb $((sz/1024)))" "$R" "$p"
    done
  else
    printf '  %snone over %sMB.%s\n' "$D" "$big" "$R"
  fi

  rm -f "$del" "$trk" "$delsorted" "$repos" "$bigf" "$loose"
}

scan_json() {
  local delsorted=$1 trk=$2; shift 2
  local roots="$*"
  printf '{\n  "roots": ['
  local first=1 r
  for r in $roots; do [ "$first" = 1 ] && first=0 || printf ','; printf '"%s"' "$r"; done
  printf '],\n  "reclaimable": [\n'
  first=1
  while IFS=$'\t' read -r kb cat p; do
    [ -n "$kb" ] || continue
    [ "$first" = 1 ] && first=0 || printf ',\n'
    printf '    {"size_kb": %s, "category": "%s", "path": "%s"}' "$kb" "$cat" "$p"
  done < "$delsorted"
  printf '\n  ],\n  "excluded_tracked": [\n'
  first=1
  while IFS=$'\t' read -r kb cat p; do
    [ -n "$kb" ] || continue
    [ "$first" = 1 ] && first=0 || printf ',\n'
    printf '    {"size_kb": %s, "category": "%s", "path": "%s"}' "$kb" "$cat" "$p"
  done < "$trk"
  local total; total=$(awk -F'\t' '{s+=$1} END{print s+0}' "$delsorted")
  printf '\n  ],\n  "total_reclaimable_kb": %s\n}\n' "$total"
}

cmd_clean() {
  local pct=90 dry=0 yes=0 pick=0 all=0 min=1; local roots=()
  while [ $# -gt 0 ]; do case "$1" in
    --pareto) pct=$2; shift 2 ;;
    --min) min=$2; shift 2 ;;
    --dry-run) dry=1; shift ;;
    --yes|-y) yes=1; shift ;;
    --pick) pick=1; shift ;;
    --all) all=1; shift ;;
    --trash) DELETE_MODE="trash"; shift ;;
    --rm) DELETE_MODE="rm"; shift ;;
    -*) die "clean: unknown option $1" ;;
    *) roots+=("$1"); shift ;;
  esac; done
  [ ${#roots[@]} -gt 0 ] || roots=(".")
  local rr=(); local r a; for r in "${roots[@]}"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done

  local del trk; del=$(mktemp); trk=$(mktemp)
  collect "$del" "$trk" "${rr[@]}"
  local delsorted; delsorted=$(mktemp)
  local min_kb=$((min*1024))
  sort -t$'\t' -k1,1 -rn "$del" | awk -F'\t' -v f="$min_kb" '$1>=f' > "$delsorted"
  if [ ! -s "$delsorted" ]; then
    printf '%sNothing to reclaim at or above %sMB (lower with --min).%s\n' "$D" "$min" "$R"; rm -f "$del" "$trk" "$delsorted"; return 0
  fi

  local chosen; chosen=$(mktemp)
  if [ "$all" = 1 ]; then
    cp "$delsorted" "$chosen"
  elif [ "$pick" = 1 ]; then
    # show all, pareto marked with ★; return whatever the user selects
    local disp; disp=$(mktemp)
    local paretoset; paretoset=$(pareto "$delsorted" "$pct")
    awk -F'\t' '{print $3}' <<EOF > "$disp.p"
$paretoset
EOF
    while IFS=$'\t' read -r kb cat p; do
      if grep -qxF "$p" "$disp.p"; then mark="★"; else mark=" "; fi
      printf '%s\t%s %-8s  %-16s %s\n' "$p" "$mark" "$(human_kb "$kb")" "$cat" "$p"
    done < "$delsorted" > "$disp"
    # tui_pick_key shows col2+, returns col1 (the path)
    printf '%s\n' "$(cat "$disp")" | tui_pick_many --prompt 'select dirs to delete (TAB) > ' \
      | awk -F'\t' '{print $1}' > "$chosen" || true
    rm -f "$disp" "$disp.p"
    [ -s "$chosen" ] || { printf '%sNo selection.%s\n' "$D" "$R"; rm -f "$del" "$trk" "$delsorted" "$chosen"; return 0; }
    # chosen currently holds only paths; refill size/cat for display
    local tmp; tmp=$(mktemp)
    while IFS= read -r p; do grep -F $'\t'"$p" "$delsorted" | head -1; done < "$chosen" > "$tmp"
    mv "$tmp" "$chosen"
  else
    pareto "$delsorted" "$pct" > "$chosen"
  fi

  # blast radius
  local n ctot
  n=$(wc -l < "$chosen" | tr -d ' ')
  ctot=$(awk -F'\t' '{s+=$1} END{print s+0}' "$chosen")
  printf '\n%sabout to delete %d dir(s), freeing %s%s%s  [mode: %s]%s\n' "$B" "$n" "$G" "$(human_kb "$ctot")" "$B" "$DELETE_MODE" "$R"
  sort -t$'\t' -k1,1 -rn "$chosen" | while IFS=$'\t' read -r kb cat p; do
    printf '  %s%-9s%s %-16s %s\n' "$G" "$(human_kb "$kb")" "$R" "$cat" "$p"
  done

  if [ "$dry" = 1 ]; then
    printf '\n%s--dry-run: nothing deleted.%s\n' "$Y" "$R"
    rm -f "$del" "$trk" "$delsorted" "$chosen"; return 0
  fi

  if [ "$yes" != 1 ]; then
    if ! tui_confirm "Delete these ${n} dir(s) via ${DELETE_MODE}?"; then
      printf '%sAborted.%s\n' "$Y" "$R"; rm -f "$del" "$trk" "$delsorted" "$chosen"; return 0
    fi
  fi

  local ok=0 fail=0 p
  while IFS=$'\t' read -r kb cat p; do
    if do_delete "$p"; then ok=$((ok+1)); else fail=$((fail+1)); fi
  done < "$chosen"
  printf '\n%sdeleted %d dir(s), freed ~%s.%s' "$G" "$ok" "$(human_kb "$ctot")" "$R"
  [ "$fail" -gt 0 ] && printf ' %s(%d refused/failed)%s' "$Y" "$fail" "$R"
  printf '\n'
  rm -f "$del" "$trk" "$delsorted" "$chosen"
}

cmd_gc() {
  local aggressive=0; local roots=()
  while [ $# -gt 0 ]; do case "$1" in
    --aggressive) aggressive=1; shift ;;
    -*) die "gc: unknown option $1" ;;
    *) roots+=("$1"); shift ;;
  esac; done
  [ ${#roots[@]} -gt 0 ] || roots=(".")
  local rr=(); local r a; for r in "${roots[@]}"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done
  local repos; repos=$(mktemp); for r in "${rr[@]}"; do find_repos "$r"; done > "$repos"
  local nice_lvl=10
  while IFS= read -r repo; do
    [ -n "$repo" ] || continue
    local before after
    before=$(du -sk "$repo/.git" 2>/dev/null | awk '{print $1}')
    printf '%s%s%s  %s.git before: %s%s\n' "$B" "$repo" "$R" "$D" "$(human_kb "${before:-0}")" "$R"
    git -C "$repo" reflog expire --expire=30.days --all 2>/dev/null || true
    if [ "$aggressive" = 1 ]; then
      nice -n "$nice_lvl" git -C "$repo" gc --prune=now --aggressive 2>&1 | tail -1 || true
    else
      nice -n "$nice_lvl" git -C "$repo" gc --prune=now 2>&1 | tail -1 || true
    fi
    git -C "$repo" worktree prune 2>/dev/null || true
    after=$(du -sk "$repo/.git" 2>/dev/null | awk '{print $1}')
    printf '  %s.git after: %s%s%s\n' "$D" "$G" "$(human_kb "${after:-0}")" "$R"
  done < "$repos"
  rm -f "$repos"
}

cmd_git_large() {
  local history=0 min_mb=5; local roots=()
  while [ $# -gt 0 ]; do case "$1" in
    --history) history=1; shift ;;
    --min) min_mb=$2; shift 2 ;;
    -*) die "git-large: unknown option $1" ;;
    *) roots+=("$1"); shift ;;
  esac; done
  [ ${#roots[@]} -gt 0 ] || roots=(".")
  local rr=(); local r a; for r in "${roots[@]}"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done
  local repos; repos=$(mktemp); for r in "${rr[@]}"; do find_repos "$r"; done > "$repos"
  local minb=$((min_mb*1024*1024))
  local out; out=$(mktemp)
  while IFS= read -r repo; do
    [ -n "$repo" ] || continue
    if [ "$history" = 1 ]; then
      git -C "$repo" rev-list --objects --all 2>/dev/null \
        | git -C "$repo" cat-file --batch-check='%(objecttype) %(objectsize) %(rest)' 2>/dev/null \
        | awk -v m="$minb" '$1=="blob" && $2>=m {print $2"\t"$3}' \
        | while IFS=$'\t' read -r sz path; do printf '%s\t(hist) %s/%s\n' "$sz" "$repo" "$path"; done
    else
      git -C "$repo" ls-tree -r -l HEAD 2>/dev/null | while IFS= read -r line; do
        local pre path sz
        pre=${line%%$'\t'*}; path=${line#*$'\t'}
        sz=$(printf '%s\n' "$pre" | awk '{print $4}')
        case "$sz" in ''|*[!0-9]*) continue ;; esac
        [ "$sz" -ge "$minb" ] && printf '%s\t%s/%s\n' "$sz" "$repo" "$path"
      done
    fi
  done < "$repos" > "$out"
  printf '%slarge files tracked in git (>=%dM)%s\n' "$B" "$min_mb" "$R"
  if [ -s "$out" ]; then
    sort -t$'\t' -k1,1 -rn "$out" | while IFS=$'\t' read -r sz p; do
      printf '  %s%-9s%s %s\n' "$RED" "$(human_kb $((sz/1024)))" "$R" "$p"
    done
    printf '\n  %sto untrack: git rm --cached <f> && echo <f> >> .gitignore%s\n' "$D" "$R"
    printf '  %sto purge from history: git filter-repo --path <f> --invert-paths%s\n' "$D" "$R"
  else
    printf '  %snone found.%s\n' "$D" "$R"
  fi
  rm -f "$repos" "$out"
}

# ── hidden headless-testable verbs ───────────────────────────────────────────
internal_candidates() {  # __candidates ROOT... → size_kb\tcategory\tpath (deletable only)
  local rr=(); local r a; for r in "$@"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done
  local del trk; del=$(mktemp); trk=$(mktemp)
  collect "$del" "$trk" "${rr[@]}"
  sort -t$'\t' -k1,1 -rn "$del"
  rm -f "$del" "$trk"
}
internal_tracked_candidates() {  # __tracked ROOT... → excluded (tracked) candidates
  local rr=(); local r a; for r in "$@"; do a=$(resolve_root "$r") || exit 1; rr+=("$a"); done
  local del trk; del=$(mktemp); trk=$(mktemp)
  collect "$del" "$trk" "${rr[@]}"
  sort -t$'\t' -k1,1 -rn "$trk"
  rm -f "$del" "$trk"
}
internal_delete() {  # __delete PATH... → delete each after revalidation
  local ok=0 fail=0 p
  for p in "$@"; do
    if do_delete "$p"; then ok=$((ok+1)); else fail=$((fail+1)); fi
  done
  printf 'deleted=%d refused=%d\n' "$ok" "$fail"
  [ "$fail" = 0 ]
}
internal_git_tracked() { is_tracked "$1" && echo "tracked" || echo "untracked"; }
internal_pareto() { pareto "$1" "$2"; }   # __pareto SORTED_DESC_FILE PCT (deterministic test seam)

# ── help ─────────────────────────────────────────────────────────────────────
show_help() {
  cat <<EOF
${B}zreclaim${R} — recon + safe cleanup of reproducible cache/build data (v$VERSION)

${Y}USAGE${R}
  ${C}zreclaim${R} <command> [PATHS...] [options]     ${D}(PATHS default to .)${R}

${Y}EXAMPLES${R}
  ${C}zreclaim scan${R} ~/Code/Versable            ${D}# rank reclaimable data, biggest first${R}
  ${C}zreclaim scan${R} --min 50 .                 ${D}# only itemize dirs >= 50MB (small ones summarized)${R}
  ${C}zreclaim scan${R} --big 100 .                ${D}# flag loose non-deletable files >= 100MB${R}
  ${C}zreclaim scan${R} --json .                   ${D}# machine-readable recon${R}
  ${C}zreclaim clean${R} ~/Code/Versable           ${D}# delete the pareto set (90%%), with confirm${R}
  ${C}zreclaim clean${R} --pick .                  ${D}# multi-select what to delete (★ = pareto)${R}
  ${C}zreclaim clean${R} --dry-run --pareto 95 .   ${D}# preview a 95%%-coverage selection${R}
  ${C}zreclaim clean${R} --trash .                 ${D}# send to Trash instead of rm${R}
  ${C}zreclaim gc${R} ~/Code/Versable              ${D}# safe git gc + reflog expire + worktree prune${R}
  ${C}zreclaim git-large${R} --history .           ${D}# large files tracked in git (report only)${R}

${Y}COMMANDS${R}
  ${C}scan${R}        Read-only. Find + size disposable dirs, ranked; flag tracked ones;
              list .git sizes, large git-tracked files, and large loose files.
  ${C}clean${R}       Delete a selection (default: pareto set). Shows blast radius + confirms.
  ${C}gc${R}          Run git gc/reflog-expire/worktree-prune on every repo under PATHS.
  ${C}git-large${R}   Report large files tracked in git. Never deletes.

${Y}OPTIONS${R}
  ${G}--min MB${R}       Size floor: itemize/consider only dirs >= MB (default: 1). Smaller
                ones are summarized (scan) or ignored (clean). Tune to taste.
  ${G}--big MB${R}       (scan) Flag loose non-deletable files >= MB (default: 50).
  ${G}--pareto PCT${R}   (clean) Coverage target for the auto-selection (default: 90)
  ${G}--pick${R}        (clean) Interactive multi-select instead of the pareto set
  ${G}--all${R}         (clean) Select every candidate above --min
  ${G}--dry-run${R}     (clean) Show what would be deleted, delete nothing
  ${G}--yes, -y${R}     (clean) Skip the confirm prompt
  ${G}--trash${R}       (clean) Send to macOS Trash (recoverable) instead of ${G}--rm${R} (default)

${Y}SAFETY${R}
  Only a closed allowlist of reproducible dirs is ever a candidate (node_modules,
  .venv, __pycache__, dist, build, .next, target, caches, ...). Size only ranks;
  it never selects. Anything ${B}tracked in git${R} is EXCLUDED and flagged. .git is
  never rm'd (use ${C}gc${R}). Protected roots (/, \$HOME, /usr, ...) are refused.
EOF
}

# ── dispatch ─────────────────────────────────────────────────────────────────
[ $# -ge 1 ] || { show_help; exit 0; }
cmd=$1; shift || true
case "$cmd" in
  scan)        cmd_scan "$@" ;;
  clean)       cmd_clean "$@" ;;
  gc)          cmd_gc "$@" ;;
  git-large)   cmd_git_large "$@" ;;
  -h|--help|help) show_help ;;
  --version)   printf '%s %s\n' "$SELF" "$VERSION" ;;
  --__candidates)      internal_candidates "$@" ;;
  --__tracked)         internal_tracked_candidates "$@" ;;
  --__delete)          internal_delete "$@" ;;
  --__git-tracked)     internal_git_tracked "$@" ;;
  --__pareto)          internal_pareto "$@" ;;
  *) die "unknown command: $cmd (try: $SELF --help)" ;;
esac
