#!/bin/bash
# dream-insights.sh — inject high-confidence behavioral rules into each session's
# system context via the SessionStart additionalContext hook field.
#
# Sources:
#   1. insight-digest.md — synthesized summary (refreshed every 3h by daemon)
#   2. associations.json — top rules by confidence, deduplicated
#
# Output: JSON {"additionalContext": "..."} to stdout, or nothing (silent exit)
#         if no data is available.

SUBCON="$HOME/.claude/subconscious/dreams"
DIGEST_FILE="$SUBCON/insight-digest.md"
ASSOC_FILE="$SUBCON/associations.json"

# Need at least one source
[ -f "$DIGEST_FILE" ] || [ -f "$ASSOC_FILE" ] || exit 0

python3 - "$DIGEST_FILE" "$ASSOC_FILE" <<'PYEOF'
import sys, json, os

digest_path = sys.argv[1]
assoc_path = sys.argv[2]

parts = []

# Part 1: Digest summary (compact, pre-synthesized)
if os.path.isfile(digest_path):
    try:
        with open(digest_path, 'r', encoding='utf-8', errors='replace') as f:
            digest = f.read().strip()
        if digest:
            parts.append(digest)
    except OSError:
        pass

# Part 2: Top behavioral rules from associations (structured, deduplicated)
if os.path.isfile(assoc_path):
    try:
        with open(assoc_path, 'r', encoding='utf-8', errors='replace') as f:
            assocs = json.load(f)
    except (OSError, json.JSONDecodeError):
        assocs = []

    # i-dream dreams over the user's transcripts, which lately are heavy on
    # i-dream's OWN development — so it produces "rules" about maintaining its
    # own pattern store. Those don't make the user's Claude sharper at their
    # actual work; drop them so the injection stays high-signal.
    selfref = (
        "patterns.json", "deduplicate pattern", "dedupe pattern", "merge these",
        "wal-migration", "wal migration", "pattern slots", "seen_count",
        "fuzzy-match against existing", "persisting a new pattern",
        "association graph", "pattern store", "before inserting a new pattern",
        "into one pattern", "union of their evidence", "extracted pattern",
        "merge them into", "new pattern", "existing patterns", "per-pattern",
    )

    # Filter: actionable, has a rule, confidence >= 0.82, not self-referential.
    rules = []
    for a in assocs:
        rule = a.get('suggested_rule', '')
        conf = a.get('confidence', 0)
        if a.get('actionable') and rule and conf >= 0.82:
            if any(kw in rule.lower() for kw in selfref):
                continue
            rules.append((conf, rule))

    # Sort by confidence descending
    rules.sort(key=lambda x: -x[0])

    # Deduplicate by normalized prefix (first 60 chars, lowered)
    seen = set()
    unique_rules = []
    for conf, rule in rules:
        key = rule[:60].lower().strip()
        if key not in seen:
            seen.add(key)
            unique_rules.append((conf, rule))

    # Cap tight — a few high-signal rules beat a wall the agent skims past.
    unique_rules = unique_rules[:8]

    if unique_rules:
        rule_lines = []
        for conf, rule in unique_rules:
            rule_lines.append(f"[{conf:.2f}] {rule}")
        parts.append(
            "## Top Behavioral Rules (from dream consolidation)\n"
            + "\n".join(rule_lines)
        )

# Part 3: atone TL;DR (top mistake patterns + affirmed behaviors).
# Prepended (not appended) so it survives the 3500-char cap — atone is the
# more action-shape-specific content vs dream's free-form insights.
# _tldr.txt is regenerated by atone-consolidate.sh on every event add. Here we
# enrich its weak mistake lines (where the description just echoes the slug)
# with each pattern's `precheck` from the event log — so the injection carries
# the at-action-time check ("do this instead"), not a bare label.
import re
_atone_dir = os.path.expanduser("~/.claude/atone")
_atone_tldr = os.path.join(_atone_dir, "derived/_tldr.txt")
_atone_tldr_off = os.path.join(_atone_dir, ".tldr-off")
if os.path.isfile(_atone_tldr) and not os.path.isfile(_atone_tldr_off):
    try:
        with open(_atone_tldr, 'r', encoding='utf-8', errors='replace') as f:
            tldr = f.read().strip()

        # slug -> latest precheck (fallback fix) from the event log.
        prechecks = {}
        ev_path = os.path.join(_atone_dir, "events.jsonl")
        if os.path.isfile(ev_path):
            with open(ev_path, 'r', encoding='utf-8', errors='replace') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        o = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    s = o.get('slug')
                    pc = (o.get('precheck') or o.get('fix') or '').strip()
                    if s and pc:
                        prechecks[s] = pc  # latest wins

        # Rewrite "⚠️ [SEV, Nx] slug — <weak desc>" → "... slug → <precheck>"
        # only when the description merely echoes the slug (no real guidance).
        line_re = re.compile(r'^(\s*⚠️?\s*\[[^\]]*\]\s*)(\S+)\s+—\s+(.*)$')
        out_lines = []
        for ln in tldr.splitlines():
            m = line_re.match(ln)
            if m:
                prefix, slug, desc = m.group(1), m.group(2), m.group(3).strip()
                pc = prechecks.get(slug)
                if pc and (desc == slug or len(desc) <= len(slug) + 3):
                    ln = f"{prefix}{slug} → {pc}"
            out_lines.append(ln)
        tldr = "\n".join(out_lines)

        if tldr:
            parts.insert(0, "### Atone — patterns to watch\n" + tldr)
    except OSError:
        pass

if not parts:
    sys.exit(0)

header = (
    "## Dream Insights + Atone (i-dream + atone)\n"
    "_High-confidence rules from background memory consolidation, plus mistake/affirmation "
    "patterns from the atone system. Behavioral directives — read once per session._\n\n"
)

content = header + "\n\n".join(parts)

# Hard cap at 3500 chars to stay lean
if len(content) > 3500:
    content = content[:3450] + "\n...(truncated)"

print(json.dumps({"additionalContext": content}))
PYEOF
