#!/usr/bin/env bash
# inject-dream-insights.sh — extract HIGH CONFIDENCE dream insights and inject
# them into ~/.claude/skills/runtime-notes.md under an "## i-dream auto-insights"
# section.
#
# Usage:
#   bash ~/.claude/scripts/dream/inject-dream-insights.sh
#
# Reads:   ~/.claude/subconscious/dreams/insights.md
# Writes:  ~/.claude/skills/runtime-notes.md  (section prepend/update)
#
# Idempotent: if no new insights since last run, runtime-notes.md is untouched.
# Uses file locking via ~/.claude/skills/shared/lock-file.sh.
#
# High-confidence threshold: conf >= 0.80
# Maximum insights injected: 10 (highest confidence first)
#
# Called by: post-wake hook, manual invocation

set -euo pipefail

INSIGHTS_SRC="${HOME}/.claude/subconscious/dreams/insights.md"
RUNTIME_NOTES="${HOME}/.claude/skills/runtime-notes.md"
CLAUDEW_DIR="${HOME}/.claude/claudew"
LAST_RUN_FILE="${CLAUDEW_DIR}/inject-last-run"
LOCK_SCRIPT="${HOME}/.claude/skills/shared/lock-file.sh"
HIGH_CONF_THRESHOLD="0.80"
MAX_INSIGHTS=10
SECTION_HEADER="## i-dream auto-insights"

mkdir -p "$CLAUDEW_DIR"

# --- File lock ---
if [[ -f "$LOCK_SCRIPT" ]]; then
    bash "$LOCK_SCRIPT" acquire "$RUNTIME_NOTES" "inject-dream-insights" || {
        echo "inject-dream-insights: lock busy, skipping." >&2
        exit 0
    }
    trap 'bash "$LOCK_SCRIPT" release "$RUNTIME_NOTES" "inject-dream-insights" 2>/dev/null || true' EXIT
fi

# --- Staleness check ---
if [[ -f "$LAST_RUN_FILE" && -f "$INSIGHTS_SRC" ]]; then
    if [[ "$INSIGHTS_SRC" -ot "$LAST_RUN_FILE" ]]; then
        echo "inject-dream-insights: insights.md unchanged since last run, skipping." >&2
        exit 0
    fi
fi

# --- Extract high-confidence insights ---
# Format in insights.md:
#   ### Insight (conf=0.88)
#   > <description>
#   **Rule:** <rule text>
#
# We parse blocks: collect conf value + Rule text for each block

if [[ ! -f "$INSIGHTS_SRC" ]]; then
    echo "inject-dream-insights: $INSIGHTS_SRC not found, skipping." >&2
    exit 0
fi

# Use Python for reliable multi-line parsing
EXTRACTED=$(python3 - "$INSIGHTS_SRC" "$HIGH_CONF_THRESHOLD" "$MAX_INSIGHTS" <<'PYEOF'
import sys, re

src_file = sys.argv[1]
threshold = float(sys.argv[2])
max_n = int(sys.argv[3])

with open(src_file, 'r') as f:
    content = f.read()

# Split on "### Insight" boundaries
blocks = re.split(r'(?=### Insight)', content)

insights = []
for block in blocks:
    # Extract confidence
    conf_match = re.search(r'\(conf=([\d.]+)\)', block)
    if not conf_match:
        continue
    conf = float(conf_match.group(1))
    if conf < threshold:
        continue

    # Extract the Rule line
    rule_match = re.search(r'\*\*Rule:\*\*\s*(.+?)(?:\n\n|\n_Patterns|\Z)', block, re.DOTALL)
    if not rule_match:
        continue
    rule = ' '.join(rule_match.group(1).strip().split())  # normalize whitespace

    # Extract description (first > line)
    desc_match = re.search(r'^>\s*(.+?)(?:\n\n|\n\*\*Rule)', block, re.DOTALL | re.MULTILINE)
    desc = ''
    if desc_match:
        desc = ' '.join(desc_match.group(1).strip().split())
        # Truncate long descriptions
        if len(desc) > 120:
            desc = desc[:117] + '...'

    # Extract wake cycle date from block context if available
    insights.append((conf, desc, rule))

# Sort descending by confidence
insights.sort(key=lambda x: x[0], reverse=True)
insights = insights[:max_n]

for conf, desc, rule in insights:
    print(f"CONF:{conf:.2f}|DESC:{desc}|RULE:{rule}")
PYEOF
)

if [[ -z "$EXTRACTED" ]]; then
    echo "inject-dream-insights: no high-confidence insights found (threshold=${HIGH_CONF_THRESHOLD})." >&2
    exit 0
fi

# --- Build the section content ---
TODAY=$(date +%Y-%m-%d)
INSIGHT_COUNT=$(echo "$EXTRACTED" | wc -l | tr -d ' ')

NEW_SECTION="${SECTION_HEADER}
<!-- auto-generated by inject-dream-insights.sh on ${TODAY} — ${INSIGHT_COUNT} insights (conf>=${HIGH_CONF_THRESHOLD}) -->

"

while IFS= read -r line; do
    conf=$(echo "$line" | sed 's/CONF:\([^|]*\)|.*/\1/')
    rule=$(echo "$line" | sed 's/.*|RULE://')
    # Truncate rule to ~200 chars for brevity
    if [[ ${#rule} -gt 200 ]]; then
        rule="${rule:0:197}..."
    fi
    NEW_SECTION+="- **[conf=${conf}]** ${rule}
"
done <<< "$EXTRACTED"

NEW_SECTION+="
---
"

# --- Inject or update section in runtime-notes.md ---
if [[ ! -f "$RUNTIME_NOTES" ]]; then
    # Create from scratch
    printf "# Skill Runtime Notes\n\nAppend-only log of post-run insights from every skill execution.\nNewest entries appear at the top. Each entry is prepended by the agent after the skill completes.\n\n%s\n" "$NEW_SECTION" > "$RUNTIME_NOTES"
    echo "inject-dream-insights: created runtime-notes.md with ${INSIGHT_COUNT} insights." >&2
else
    existing=$(cat "$RUNTIME_NOTES")
    if echo "$existing" | grep -qF "$SECTION_HEADER"; then
        # Update existing section: replace from header to the next "---\n" after it
        python3 - "$RUNTIME_NOTES" "$SECTION_HEADER" "$NEW_SECTION" <<'PYEOF'
import sys, re

notes_file = sys.argv[1]
header = sys.argv[2]
new_section = sys.argv[3]

with open(notes_file, 'r') as f:
    content = f.read()

# Replace from SECTION_HEADER up to (and including) the following standalone "---\n"
pattern = re.escape(header) + r'.*?(?<=\n)---\n'
replacement = new_section
new_content, n = re.subn(pattern, replacement, content, count=1, flags=re.DOTALL)
if n == 0:
    # Fallback: just prepend the section after the first line (the title)
    lines = content.split('\n', 1)
    new_content = lines[0] + '\n\n' + new_section + (lines[1] if len(lines) > 1 else '')

with open(notes_file, 'w') as f:
    f.write(new_content)

print(f"inject-dream-insights: updated existing section ({n} replacement(s)).", file=__import__('sys').stderr)
PYEOF
    else
        # Prepend section after the first line of the file
        python3 - "$RUNTIME_NOTES" "$NEW_SECTION" <<'PYEOF'
import sys

notes_file = sys.argv[1]
new_section = sys.argv[2]

with open(notes_file, 'r') as f:
    content = f.read()

# Insert after the first heading line
lines = content.split('\n')
insert_at = 0
for i, line in enumerate(lines):
    if line.startswith('#'):
        insert_at = i + 1
        break

lines.insert(insert_at, '\n' + new_section)
with open(notes_file, 'w') as f:
    f.write('\n'.join(lines))

print("inject-dream-insights: prepended new section.", file=__import__('sys').stderr)
PYEOF
    fi
fi

# --- Mark last-run timestamp ---
touch "$LAST_RUN_FILE"
echo "inject-dream-insights: done. ${INSIGHT_COUNT} insights injected into runtime-notes.md." >&2
