#!/bin/bash
# Weekly mistake-patterns graduation scan.
#
# Loads via launchd at ~/Library/LaunchAgents/com.alcatraz.mistake-patterns-graduation.plist
# Cadence: every Wednesday at 10:00 IST (per user request 2026-05-04).
#
# Reads ~/.claude/mistake-patterns.md, scans for graduation candidates
# (3+ occurrences over > 4 weeks → propose moving to rules/*.md or a hook),
# stale candidates (1 occurrence > 8 weeks old → drop), and healthy patterns.
# Writes report to ~/.claude/topics/mistake-patterns-graduation-YYYY-MM-DD.md.
#
# Manual run: bash ~/.claude/scripts/mistake-patterns-graduation.sh
# Disable: launchctl unload ~/Library/LaunchAgents/com.alcatraz.mistake-patterns-graduation.plist

set -euo pipefail

PATTERNS_FILE="$HOME/.claude/mistake-patterns.md"
TOPICS_DIR="$HOME/.claude/topics"
TODAY="$(date +%Y-%m-%d)"
OUTPUT="$TOPICS_DIR/mistake-patterns-graduation-$TODAY.md"

mkdir -p "$TOPICS_DIR"

# Bail gracefully if the patterns file is missing.
if [ ! -f "$PATTERNS_FILE" ]; then
    echo "# Mistake patterns graduation scan — $TODAY" > "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "**Skipped**: $PATTERNS_FILE not found." >> "$OUTPUT"
    exit 0
fi

# Hand the scan off to claude --print non-interactively. The prompt is
# self-contained — the agent reads the file inline rather than relying on
# any session context.
PROMPT=$(cat <<'EOF'
You are doing the weekly mistake-patterns graduation scan.

Read ~/.claude/mistake-patterns.md. For each pattern (a "## Pattern: <name>" block), count distinct "Triggered: YYYY-MM-DD" dates and note the date range (oldest to newest).

Bucket each pattern:
- **Graduation candidates**: 3+ distinct trigger dates spanning > 4 weeks. These have proven recurrence and should move to a proper rules/*.md entry or a hook.
- **Stale candidates**: 1 occurrence > 8 weeks old. Drop them.
- **Healthy patterns**: recent (< 8 weeks) and lower frequency. Keep, no action.

Output a markdown report with these three sections. For graduation candidates, include a proposed rule sentence OR a sketched hook spec. For stale candidates, just list them. For healthy, just count + list briefly.

Tone: terse, no fluff. End with a one-sentence verdict on whether the pattern collection is healthy (mostly recent + low-frequency) or accumulating debt (lots of graduation candidates).

Do NOT modify mistake-patterns.md itself. Report only.
EOF
)

# Find the claude CLI binary. Try $PATH first, then common install
# locations. Both interactive `bash <script>` and launchctl-spawned
# bash strip aliases/functions, so we must locate a real binary.
CLAUDE_BIN=""
for candidate in \
    "$(command -v claude 2>/dev/null)" \
    "$HOME/.claude/local/claude" \
    "$HOME/.local/bin/claude" \
    "/opt/homebrew/bin/claude" \
    "/usr/local/bin/claude" \
; do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        CLAUDE_BIN="$candidate"
        break
    fi
done

if [ -z "$CLAUDE_BIN" ]; then
    echo "# Mistake patterns graduation scan — $TODAY" > "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "**Failed**: \`claude\` CLI not found in PATH or common install locations." >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "Searched:" >> "$OUTPUT"
    echo "- \$(command -v claude) → $(command -v claude 2>/dev/null || echo 'not in PATH')" >> "$OUTPUT"
    echo "- \$HOME/.claude/local/claude" >> "$OUTPUT"
    echo "- \$HOME/.local/bin/claude" >> "$OUTPUT"
    echo "- /opt/homebrew/bin/claude" >> "$OUTPUT"
    echo "- /usr/local/bin/claude" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "Edit the script's CLAUDE_BIN search list to add the actual path." >> "$OUTPUT"
    exit 1
fi

{
    echo "# Mistake patterns graduation scan — $TODAY"
    echo ""
    echo "_Generated by ~/.claude/scripts/mistake-patterns-graduation.sh using ${CLAUDE_BIN}_"
    echo ""
    "$CLAUDE_BIN" --print "$PROMPT" 2>&1
} > "$OUTPUT"

# Surface a notification (osascript — UN crashes for unbundled processes).
osascript -e "display notification \"Report at ~/.claude/topics/mistake-patterns-graduation-$TODAY.md\" with title \"Mistake patterns scan complete\" sound name \"Glass\"" 2>/dev/null || true

echo "✓ Wrote $OUTPUT"
