#!/usr/bin/env bash
# ~/.claude/scripts/dev-servers/gen-nginx-conf.sh
# Generate nginx server blocks for .test domains from the port registry.
#
# Usage:
#   gen-nginx-conf.sh [--dry-run] [--output <path>]
#
# Reads ~/.claude/scratchpad/global/port-registry.md and generates nginx server
# blocks. Each registered project gets:
#   pair:   <name>.test     → frontend port (30xx)  with WebSocket/HMR support
#           <name>-api.test → backend port  (50xx)
#   server: <name>.test     → backend port  (50xx)
#
# After running, reload nginx:
#   sudo nginx -t && sudo nginx -s reload
#
# NOTE: The local.PORT.run pattern in local-proxy.conf already provides zero-config
# access to any port. .test domains are a convenience alias on top of that.

set -euo pipefail

REGISTRY="$HOME/.claude/scratchpad/global/port-registry.md"
DEFAULT_OUTPUT="/opt/homebrew/etc/nginx/servers/local-dev.conf"

DRY_RUN=0
OUTPUT="$DEFAULT_OUTPUT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --output)  OUTPUT="$2"; shift 2 ;;
    --help|-h) echo "Usage: gen-nginx-conf.sh [--dry-run] [--output <path>]"; exit 0 ;;
    *) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Generate nginx config via Python (handles markdown table parsing cleanly)
GENERATED=$(python3 - "$REGISTRY" <<'PYEOF'
import sys, datetime

registry_path = sys.argv[1]

with open(registry_path) as f:
    lines = f.readlines()

# Parse ONLY the main port registry table (stop at ## sections).
# Valid port rows: col[1] is a numeric port (30xx or 50xx).
import re

projects = {}  # sanitized_name → {frontend: port, backend: port}
in_main_table = False

for line in lines:
    stripped = line.strip()
    # Stop parsing at any ## section after the table starts
    if stripped.startswith('## ') and in_main_table:
        break
    if stripped.startswith('| Port'):
        in_main_table = True
        continue
    if not stripped.startswith('|') or '---' in stripped:
        continue
    cols = [c.strip() for c in stripped.split('|')]
    if len(cols) < 5:
        continue
    port, service, name = cols[1], cols[2], cols[3]
    # Only accept numeric ports (30xx/50xx); skip header-like rows
    if not re.match(r'^\d{4}$', port):
        continue
    if not service or not name:
        continue
    # Sanitize project name for use as nginx server_name:
    # lowercase, replace spaces/parens/special chars with hyphens, collapse
    safe_name = re.sub(r'[^a-z0-9-]', '-', name.lower())
    safe_name = re.sub(r'-{2,}', '-', safe_name).strip('-')
    if not safe_name:
        continue
    svc = service.lower()
    if safe_name not in projects:
        projects[safe_name] = {'display': name}
    if 'frontend' in svc or port.startswith('3'):
        projects[safe_name]['frontend'] = port
    else:
        projects[safe_name]['backend'] = port

def nginx_block(server_name, port, websocket=True):
    """
    Generate an nginx server block with Host rewrite.
    The Host rewrite (localhost:PORT) is critical for Vite — without it,
    Vite's allowedHosts security check rejects the request with 403.
    """
    ws_lines = ""
    if websocket:
        ws_lines = (
            "\n        # WebSocket support (Vite HMR, SvelteKit, Next.js dev server)"
            "\n        proxy_http_version  1.1;"
            "\n        proxy_set_header    Upgrade    $http_upgrade;"
            "\n        proxy_set_header    Connection \"upgrade\";"
        )
    return (
        f"server {{\n"
        f"    listen 80;\n"
        f"    server_name {server_name};\n\n"
        f"    location / {{\n"
        f"        proxy_pass          http://127.0.0.1:{port};\n"
        f"        # Rewrite Host so Vite/Next.js allowedHosts check passes\n"
        f"        proxy_set_header    Host              localhost:{port};\n"
        f"        proxy_set_header    X-Real-IP         $remote_addr;\n"
        f"        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;\n"
        f"        proxy_set_header    X-Forwarded-Proto $scheme;{ws_lines}\n"
        f"        proxy_read_timeout  300s;\n"
        f"        proxy_send_timeout  300s;\n"
        f"        proxy_buffering     off;\n"
        f"    }}\n"
        f"}}\n"
    )

out = [
    f"# Auto-generated by gen-nginx-conf.sh — {datetime.date.today()}",
    "# Do not edit manually. Regenerate: bash ~/.claude/scripts/dev-servers/gen-nginx-conf.sh",
    "# Then reload: sudo nginx -t && sudo nginx -s reload",
    "#",
    "# Zero-config alternative (no .test needed): http://local.PORT.run",
    "# (requires dnsmasq with address=/.run/127.0.0.1 and nginx local-proxy.conf)",
    "",
]

for name, ports in sorted(projects.items()):
    fe = ports.get('frontend')
    be = ports.get('backend')
    display = ports.get('display', name)
    if fe and be:
        out.append(f"# {display} (pair: {name}.test → :{fe}, {name}-api.test → :{be})")
        out.append(nginx_block(f"{name}.test", fe, websocket=True))
        out.append(nginx_block(f"{name}-api.test", be, websocket=False))
    elif be:
        out.append(f"# {display} (server: {name}.test → :{be})")
        out.append(nginx_block(f"{name}.test", be, websocket=False))
    elif fe:
        out.append(f"# {display} (frontend: {name}.test → :{fe})")
        out.append(nginx_block(f"{name}.test", fe, websocket=True))

print('\n'.join(out))
PYEOF
)

if [[ "$DRY_RUN" == "1" ]]; then
  echo "=== DRY RUN (would write to: ${OUTPUT}) ==="
  echo ""
  echo "$GENERATED"
  echo ""
  echo "Run without --dry-run to write."
else
  echo "$GENERATED" > "$OUTPUT"
  echo "Written: ${OUTPUT}"
  echo ""
  echo "Projects configured:"
  echo "$GENERATED" | grep "^# " | grep -v "Auto-gen\|Do not\|Then\|Zero-config" | sed 's/^# /  /'
  echo ""
  echo "Test config and reload nginx:"
  echo "  sudo nginx -t && sudo nginx -s reload"
fi
